# Generated by Django 3.1.4 on 2021-01-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210120_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshop',
            name='year',
            field=models.TextField(),
        ),
    ]
