# Generated by Django 3.1.4 on 2021-01-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210124_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshop',
            name='is_favorite1',
            field=models.BooleanField(default=False),
        ),
    ]
